### ISSUE TITLE
LeYolo Obb

### ISSUE THREAD

**Issue by SwEngine** [LilianHollard/LeYOLO#1]
Thanks for such a great work! Do you have any plan to release obb version?

**Comment by LilianHollard** [comment]
Hi! I appreciate your interest! 

I did not train the network with OBB head; however, since I used the Ultralytics API, you should be able to replace one of the LeYOLO.yaml with OBB instead of Detect.
Therefore, you can use both the backbone and the neck of LeYOLO combined with the YOLOv8 OBB head (However, I can't say if the training will be more interesting than the base version of YOLOv8-OBB)

Here is a minimal example of LeYOLO backbone + neck with yolov8 OBB head : 

```yaml
Change LeYOLONano.yaml (or any other yaml file) : 
- [[24, 29, 34], 1, Detect, [nc]]  # Detect(P3, P4, P5)
to
- [[24, 29, 34], 1, OBB, [nc,1]]  # Detect(P3, P4, P5)
```

I tried using the dota8 dataset to check if the training works correctly, and it seems to work!!

I will try on my side to see if there is any possible update for LeYOLO to have any "lightweight" OBB head, but please let me know if you have any updates.
