### ISSUE TITLE
Incoherent parameter number in the paper

### ISSUE THREAD

**Issue by edofazza** [LilianHollard/LeYOLO#18]
Hi,

I went through your paper on ArXiv and noticed that some models present different value of parameters based on the position in the table. Although, it is not specify why. I believe this is related to different input sizes. However, could you list correctly the number of parameters for each model based on the input size.  Thank you

**Comment by LilianHollard** [comment]
Hi, thank you for your question! 

The number of parameters is not related to the input size. Only FLOP is associated with the input.
For scaling information, see Table 12 in the Appendix; it is related to the channel expansion ratio and layer depths (repetition). 
* Nano is the base number of parameter scaling: channels x1, layers x1
* Small is the following scale with only channels scaling: channels x1.33, layers x1
* Medium is scale with both: channels x1.33, layers x1.33
* Large is the same scale as Medium; however, we increase the input size. Therefore, Large uses the same amount of parameters but more computation (FLOP) since the input is more significant (768p).

I hope it answers your interrogation :)

**Comment by edofazza** [comment]
Hi, thank you for the clarification! :)
