### ISSUE TITLE
More details about the Figure 7.

### ISSUE THREAD

**Issue by AntonioConsiglio** [LilianHollard/LeYOLO#2]
Thankf for your work. Reading the paper has been really a pleasure.

Can I ask more details about this Figure below:

![image](https://github.com/LilianHollard/LeYOLO/assets/77753494/36441ccf-2a78-4b78-b272-cfaa69105441)

In particular, what is the Input size for the other YOLOv?-n models? 640 ?
Thanks.

**Comment by LilianHollard** [comment]
Hi! Thank you very much. I am glad you liked the paper.

My apologies if it was not sufficiently self-explanatory. I used all the base other YOLO models with a similar number of parameters or FLOP to compare LeYOLO with. 
Therefore, I did the benchmark with the input size described in each respective paper (or git),**which is 640p**.
 
LeYOLOsmall at 320p is as good as YOLOv5n at 640p regarding mAP on MSCOCO. It was interesting to see how great and fast having a 320p solution might be.

Also, since the legend of LeYOLO might be too small, here are the details about the speed-test input size (from LeYOLOx left to right) :
320p, 320p, 480p, 480p, 480p, 640p, 640p, 768p

I hope this answers your question!
